#!/bin/sh
tail -n50 /Users/Fabricio/workspace/chom/MIRA_assembling/repetition/blast/Chom_Readrepeats_RepBase_v17_06/Chom_Readrepeats_RepBase_v17_06-summary.txt > ~/Dropbox/USP/IC/Chom_Readrepeats_RepBase_v17_06-summary.txt
tail -n50 /Users/Fabricio/workspace/chom/MIRA_assembling/repetition/blast/Chom_Readrepeats_RepBase_v17_06/Chom_Readrepeats_RepBase_v17_06-table.txt > ~/Dropbox/USP/IC/Chom_Readrepeats_RepBase_v17_06-table.txt
